<a href="https://colab.research.google.com/github/segravjf/python_practice/blob/main/filtering_student_info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Filtering student information with Pandas

Suppose you have a dataframe, df, with the following records:


    

    
Age	Favorite Color	Grade	Name
20	blue	88	Willard Morris
19	blue	95	Al Jennings
22	yellow	92	Omar Mullins
21	green	70	Spencer McDaniel

    

    
The dataframe is showing information about students. Write code using Python Pandas to select the rows where the students' favorite color is green or yellow and their grade is between 85-95 (inclusive).

In [1]:
## Import key modules
import pandas as pd
import numpy as np

In [2]:
## Create dataframe
age = [20,19,22,21]
fav_color = ['blue','blue','yellow','green']
grade = [88,95,92,70]
name = ['Willard Morris','Al Jennings','Omar Mullins','Spencer McDaniel']

df = pd.DataFrame({
    'age':age,
    'favorite_color':fav_color,
    'grade':grade,
    'name':name
})

df

   age favorite_color  grade              name
0   20           blue     88    Willard Morris
1   19           blue     95       Al Jennings
2   22         yellow     92      Omar Mullins
3   21          green     70  Spencer McDaniel

In [3]:
## Filter to rows where the students' favorite color is green or yellow and their grade is between 85 and 95
cond1 = df['favorite_color'].str.contains('green|yellow',regex=True)
cond2 = 85 <= df['grade']
cond3 = 95 >= df['grade']

filt = df[np.logical_and(cond1, cond2, cond3)]

filt

   age favorite_color  grade          name
2   22         yellow     92  Omar Mullins